/**
 * Wire and domain types for the Gmail REST API subset this package covers.
 * @module
 */

/** The `installed`/`web` block of a Google Cloud Console OAuth client download. */
export interface ClientSecret {
  /** OAuth 2.0 client id from the Google Cloud console. */
  clientId: string;
  /** OAuth 2.0 client secret. Never log it. */
  clientSecret: string;
}

/** One mailbox's OAuth grant as persisted by a {@link TokenStore}. */
export interface OAuthCredential {
  /** Long-lived at Google until revoked. The secret that matters. */
  refreshToken: string;
  /** ~1h. Refreshed transparently by the client. */
  accessToken: string;
  /** ISO 8601 UTC. */
  accessTokenExpiresAt: string;
  /** Mailbox address, from `users.getProfile`. Used as the store key. */
  email: string;
  /** Space-separated scopes Google actually granted. */
  scope: string;
  /** ISO 8601 UTC of the login that minted the refresh token. */
  savedAt: string;
}

/**
 * Where credentials live. The library ships {@link FileTokenStore}; callers with their
 * own policy (TTL sweeps, keychains, per-tenant keying) implement this instead.
 */
export interface TokenStore {
  /** `account` omitted → the store's default account, or null if none. */
  load(account?: string): Promise<OAuthCredential | null>;
  /** Insert or replace the credential for `cred.email`. */
  save(cred: OAuthCredential): Promise<void>;
  /** Forget `account` (case-insensitive). */
  delete(account: string): Promise<void>;
  /** Mailbox addresses with a stored credential. */
  list(): Promise<string[]>;
}

// ── Gmail API wire shapes (the fields we read; the API returns more) ──────────

/** One MIME header on a message part, as Gmail returns it. */
export interface MessagePartHeader {
  /** Header name as sent, e.g. `Content-Disposition`. */
  name: string;
  /** Header value as sent. */
  value: string;
}

/** Body of a MIME part. Large bodies carry an `attachmentId` instead of inline `data`. */
export interface MessagePartBody {
  /** Id for `users.messages.attachments.get`. Ephemeral; do not persist. */
  attachmentId?: string;
  /** Decoded size in bytes. */
  size?: number;
  /** base64url. Present for small inline bodies, absent when `attachmentId` is set. */
  data?: string;
}

/** A node in a message's MIME tree, as Gmail returns it. */
export interface MessagePart {
  /** Gmail's part id, e.g. `0.1`. */
  partId?: string;
  /** MIME type of this part. */
  mimeType?: string;
  /** Filename for attachment parts; empty for body parts. */
  filename?: string;
  /** Headers on this part. */
  headers?: MessagePartHeader[];
  /** Body or attachment pointer for this part. */
  body?: MessagePartBody;
  /** Child parts for multipart types. */
  parts?: MessagePart[];
}

/** A Gmail message as returned by `users.messages.get`. */
export interface Message {
  /** Gmail message id (hex). */
  id: string;
  /** Id of the thread this message belongs to. */
  threadId: string;
  /** Label ids applied to the message. */
  labelIds?: string[];
  /** Short plain-text preview generated by Gmail. */
  snippet?: string;
  /** Mailbox history id at last change. */
  historyId?: string;
  /** ms since epoch as a string. */
  internalDate?: string;
  /** Gmail's estimate of the message size in bytes. */
  sizeEstimate?: number;
  /** Root of the MIME tree; absent for `raw`/`minimal` formats. */
  payload?: MessagePart;
  /** Only with `format=raw`. */
  raw?: string;
}

/** A Gmail thread as returned by `users.threads.get`. */
export interface Thread {
  /** Gmail thread id (hex). */
  id: string;
  /** Mailbox history id at last change. */
  historyId?: string;
  /** Messages in the thread, oldest first. */
  messages?: Message[];
}

/** Response of `users.messages.list`. */
export interface MessageListResponse {
  /** Matching message ids with their thread ids; absent when there are no results. */
  messages?: { id: string; threadId: string }[];
  /** Token for the next page, if any. */
  nextPageToken?: string;
  /** Gmail's rough count of total matches. */
  resultSizeEstimate?: number;
}

/** Response of `users.getProfile`. */
export interface Profile {
  /** The mailbox address. */
  emailAddress: string;
  /** Total messages in the mailbox. */
  messagesTotal: number;
  /** Total threads in the mailbox. */
  threadsTotal: number;
  /** Current mailbox history id. */
  historyId: string;
}

/** A Gmail label as returned by `users.labels.get`/`list`. */
export interface Label {
  /** Label id, e.g. `INBOX` or `Label_12`. */
  id: string;
  /** Display name. */
  name: string;
  /** System labels are Gmail's built-ins; user labels are custom. */
  type?: "system" | "user";
  /** Messages carrying this label. */
  messagesTotal?: number;
  /** Unread messages carrying this label. */
  messagesUnread?: number;
  /** Threads carrying this label. */
  threadsTotal?: number;
  /** Unread threads carrying this label. */
  threadsUnread?: number;
}

/** Payload shape for `users.messages.get` and `users.threads.get`. */
export type MessageFormat = "full" | "metadata" | "minimal" | "raw";

// ── Domain shapes this package adds ──────────────────────────────────────────

/**
 * An attachment located in a message's MIME tree.
 *
 * `attachmentId` is NOT stable across `messages.get` calls — fetch, use, discard. Never
 * persist one and look it up later.
 */
export interface AttachmentRef {
  /** Id of the message that carries the attachment. */
  messageId: string;
  /** Filename as sent. */
  filename: string;
  /** Ephemeral id for `users.messages.attachments.get`; fetch-then-use. */
  attachmentId: string;
  /** MIME type; `application/octet-stream` when Gmail omits it. */
  mimeType: string;
  /** Bytes, per Gmail's `body.size`. */
  size: number;
  /** `Content-Disposition: inline` with a `Content-ID` — an embedded image, usually. */
  inline: boolean;
}

/** One file written by a fetch. */
export interface ManifestEntry {
  /** Id of the message the file came from. */
  messageId: string;
  /** As sent, including Gmail's ` (1)` suffixes. */
  filename: string;
  /** Basename actually written; differs from `filename` only on a collision. */
  savedAs: string;
  /** Absolute path of the written file. Absent on `dryRun`. */
  path?: string;
  /** MIME type as reported by Gmail. */
  mimeType: string;
  /** Bytes written, or Gmail's `body.size` on `dryRun`. */
  bytes: number;
  /** Hex. Absent on `dryRun`. */
  sha256?: string;
}

/** Record of one fetch run, written as `manifest.json` in `outDir`. */
export interface Manifest {
  /** Thread id, or the single message id for a message-scoped fetch. */
  source: { threadId?: string; messageId?: string };
  /** Mailbox address the fetch ran as. */
  account: string;
  /** ISO 8601 UTC. */
  fetchedAt: string;
  /** Absolute path files were written to. */
  outDir: string;
  /** Files written (or that would be written on `dryRun`). */
  files: ManifestEntry[];
  /**
   * Attachments present in the source but not written: excluded by `include`/`filenames`/
   * `inline`/`maxBytes` rules, or already on disk when `skipExisting` is set (reason starts
   * `already in <dir>`).
   */
  skipped: { messageId: string; filename: string; reason: string }[];
}
